import { createAction } from 'redux-actions'

export const ON_CHANGE = createAction("root/views/login/ON_CHANGE")
export const LOGAR_START = createAction("root/views/login/LOGAR_START")
export const LOGAR_SUCCESS = createAction("root/views/login/LOGAR_SUCCESS")
export const LOGAR_ERROR = createAction("root/views/login/LOGAR_ERROR")
export const CADASTRO_START = createAction("root/views/login/CADASTRO_START")
export const CADASTRO_SUCCESS = createAction("root/views/login/CADASTRO_SUCCESS")
export const CADASTRO_ERROR = createAction("root/views/login/CADASTRO_ERROR")
export const RECUPERAR_START = createAction("root/views/login/RECUPERAR_START")
export const RECUPERAR_SUCCESS = createAction("root/views/login/RECUPERAR_SUCCESS")
export const RECUPERAR_ERROR = createAction("root/views/login/RECUPERAR_ERROR")
export const ALTERAR_START = createAction("root/views/login/ALTERAR_START")
export const ALTERAR_SUCCESS = createAction("root/views/login/ALTERAR_SUCCESS")
export const ALTERAR_ERROR = createAction("root/views/login/ALTERAR_ERROR")
export const CONFIRMAR_START = createAction("root/views/login/CONFIRMAR_START")
export const CONFIRMAR_SUCCESS = createAction("root/views/login/CONFIRMAR_SUCCESS")
export const CONFIRMAR_ERROR = createAction("root/views/login/CONFIRMAR_ERROR")
export const STATUS_START = createAction("root/views/login/STATUS_START")
export const STATUS_SUCCESS = createAction("root/views/login/STATUS_SUCCESS")
export const STATUS_ERROR = createAction("root/views/login/STATUS_ERROR")